version: "3.8"

services:
  flask_ms:
    container_name: flask_ms
    image: flask_ms
    build:
      context: ../../services/flask_ms
      dockerfile: ../../docker/build/flask_ms/Dockerfile
      target: development
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ../../services/flask_ms:/home/app/web
    networks:
      - transit_and_transport
    networks:
      transit_and_transport:
        aliases:
          - ${FLASK_HOST}

  postgres_ms:
    container_name: flask_postgres_ms
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      transit_and_transport:
        aliases:
          - ${POSTGRES_HOST}


networks:
  transit_and_transport:
    driver: bridge

volumes:
  db_data: