version: "3.8"

services:
  flask:
    container_name: flask_ms
    image: flask_ms
    build:
      context: ../../services/flask_ms
      dockerfile: ../../docker/build/flask_ms/Dockerfile
      target: development
    environment:
      - FLASK_ENV=development
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - ../../services/flask_ms:/home/app/web
    networks:
      - transit_and_transport
    depends_on:
      - db
    networks:
      transit_and_transport:
        aliases:
          - ${FLASK_HOST}

  db:
    container_name: postgres_ms
    image: postgres:alpine3.17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      transit_and_transport:
        aliases:
          - ${POSTGRES_HOST}


networks:
  transit_and_transport:
    driver: bridge

volumes:
  db_data: